{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.arbjerg",
    "module": "lavaplayer",
    "version": "6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "dev.arbjerg",
          "module": "lava-common",
          "version": {
            "requires": "6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar",
          "url": "lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar",
          "size": 680476,
          "sha512": "b76bd90f41b44dd3e81b3a6db2c7a0e6a18e1fe8831d84f005cc858e25cac00ef521e2ccd49b2a69c904a0c2b31fbb77efd5c3516d31b60e3041b2d0743a1ac0",
          "sha256": "8f559d0ced2349600465037b92d9632ac84e83b899229ea5697d19a2e4a91a40",
          "sha1": "4f2201be095318d2a725a8d1a4a9172f87c1b98a",
          "md5": "0d99a3ae49749a952e7c0f1f229a2a8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.arbjerg",
          "module": "lavaplayer-natives",
          "version": {
            "requires": "6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT"
          }
        },
        {
          "group": "com.github.walkyst.JAADec-fork",
          "module": "jaadec-ext-aac",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.7.14"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.6"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.12.1"
          }
        },
        {
          "group": "net.iharder",
          "module": "base64",
          "version": {
            "requires": "2.3.9"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20220924"
          }
        },
        {
          "group": "dev.arbjerg",
          "module": "lava-common",
          "version": {
            "requires": "6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.25"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.10"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar",
          "url": "lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar",
          "size": 680476,
          "sha512": "b76bd90f41b44dd3e81b3a6db2c7a0e6a18e1fe8831d84f005cc858e25cac00ef521e2ccd49b2a69c904a0c2b31fbb77efd5c3516d31b60e3041b2d0743a1ac0",
          "sha256": "8f559d0ced2349600465037b92d9632ac84e83b899229ea5697d19a2e4a91a40",
          "sha1": "4f2201be095318d2a725a8d1a4a9172f87c1b98a",
          "md5": "0d99a3ae49749a952e7c0f1f229a2a8b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT-sources.jar",
          "url": "lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT-sources.jar",
          "size": 395194,
          "sha512": "98ba832520c3412cc85081e811c127946491f6b4dd69fadef11d96e992b95ccdf1ae20ffc2e74fc15953e976cbbf99abd8020dd11f75e30eedfda7e173e20806",
          "sha256": "658c37505b42feda77c94cfdce4a0ca2e67d3f8a908a999145e3635dc4749162",
          "sha1": "e460c8fbf37d993844f21ce54a41be4cbeb6cc73",
          "md5": "5b61de59984317b5c46c35c1e881037e"
        }
      ]
    }
  ]
}
